{ options
, config
, lib
, pkgs
, modulesPath
, ...
}:

# ── App Container Archetype ──────────────────────────────────────────────────
#
# Turns a NixOS Incus container into a kiosk-style graphical app accessible via
# Guacamole (VNC). Each container runs one application on a virtual X display
# served by TigerVNC (Xvnc). Guacamole on the host connects to the VNC port
# over the Incus bridge.
#
# Quick start (add to your container's default.nix):
#
#   imports = [ (modulesPath + "/virtualisation/lxc-container.nix") ];
#   frgd.archetypes.app-container = {
#     enable   = true;
#     app.package = pkgs.obsidian;
#     display  = { width = 1920; height = 1080; };
#     audio.enable = true;
#   };
#
# Building and importing the Incus image:
#
#   # Build image tarball and metadata
#   nix build .#nixosConfigurations.<hostname>.config.system.build.lxcMetadata \
#     --out-link ./result-meta
#   nix build .#nixosConfigurations.<hostname>.config.system.build.tarball \
#     --out-link ./result-rootfs
#
#   # Import into Incus on the host
#   incus image import \
#     ./result-meta/tarball/nixos-system-x86_64-linux.tar.xz \
#     ./result-rootfs/tarball/nixos-system-x86_64-linux.tar.xz \
#     --alias <hostname>
#
#   # Create container (security.nesting needed for Nix sandbox)
#   incus init <hostname> <container-name> \
#     -c security.nesting=true \
#     -c limits.cpu=2 \
#     -c limits.memory=4GiB
#
#   # Optional: mount persistent data from host storage
#   incus config device add <container-name> appdata disk \
#     source=/storage/<appname> \
#     path=/home/kiosk/<appname>
#
#   incus start <container-name>
#
# ── VNC Connection Info (for Guacamole) ─────────────────────────────────────
# Protocol : VNC
# Hostname : <container bridge IP or Incus DNS: <container-name>.incus>
# Port     : 5901 (default, or display.number + 5900)
# Auth     : None (SecurityTypes None — relying on Incus bridge isolation)
# ────────────────────────────────────────────────────────────────────────────

with lib;
with lib.frgd;
let
  cfg = config.frgd.archetypes.app-container;

  displayNum = toString cfg.display.number;
  displayWidth = toString cfg.display.width;
  displayHeight = toString cfg.display.height;
  displayDepth = toString cfg.display.depth;
  vncPort = toString cfg.vnc.port;
  kioskHome = "/var/lib/kiosk";

  # Resolve the command to run: explicit cfg.app.command wins, then
  # package.meta.mainProgram, then the package name itself.
  appCommand =
    if cfg.app.command != "" then
      cfg.app.command
    else if cfg.app.package ? meta && cfg.app.package.meta ? mainProgram then
      "${cfg.app.package}/bin/${cfg.app.package.meta.mainProgram}"
    else
      "${cfg.app.package}/bin/${cfg.app.package.pname or cfg.app.package.name}";

  # Build the xstartup script that VNC runs when a session starts.
  xstartupScript = pkgs.writeScript "xstartup" (
    ''
      #!/bin/sh
      # Generated by frgd.archetypes.app-container — do not edit manually.
      # Set environment variables for the app.
    ''
    + concatStringsSep "\n" (mapAttrsToList (k: v: "export ${k}=${escapeShellArg v}") cfg.app.extraEnv)
    + ''

      # Launch the application; the container shuts down the VNC session when it exits.
      exec ${appCommand} ${cfg.app.extraArgs}
    ''
  );

in
{
  options.frgd.archetypes.app-container = with types; {
    enable = mkBoolOpt false "Whether to enable the graphical app container archetype.";

    app = {
      package = mkOpt package pkgs.xterm "The application package to install and launch.";
      command = mkOpt str "" "Full path to the command to run (defaults to the package's main binary).";
      extraArgs = mkOpt str "" "Extra command-line arguments appended to the app command.";
      extraEnv = mkOpt (attrsOf str) { } "Extra environment variables set in the xstartup script.";
    };

    display = {
      number = mkOpt int 1 "X display number. VNC port = 5900 + this number (default :1 → port 5901).";
      width = mkOpt int 1280 "Display width in pixels.";
      height = mkOpt int 800 "Display height in pixels.";
      depth = mkOpt int 24 "Color depth (bits per pixel).";
    };

    vnc = {
      port = mkOpt port 5901 "VNC listen port. Should equal 5900 + display.number.";
      listenHost =
        mkOpt str "0.0.0.0"
          "VNC bind address. Defaults to all interfaces (bridge isolation provides security).";
    };

    audio = {
      enable = mkBoolOpt false "Enable PulseAudio null-sink for Guacamole audio forwarding.";
      port =
        mkOpt port 4713
          "PulseAudio TCP module port. Configure the matching port in frgd.services.guacamole.connections.";
    };
  };

  config = mkIf cfg.enable {

    assertions = [
      {
        assertion = cfg.vnc.port == (cfg.display.number + 5900);
        message = "frgd.archetypes.app-container: vnc.port (${vncPort}) should equal display.number (${displayNum}) + 5900. Adjust one to match the other.";
      }
    ];

    # ── Base LXC archetype (SSH, Tailscale, SOPS, doas, node-exporter) ────
    frgd.archetypes.lxc = enabled;

    # ── Packages: TigerVNC + the application + optional PulseAudio ────────
    environment.systemPackages = [
      pkgs.tigervnc
      cfg.app.package
    ]
    ++ optional cfg.audio.enable pkgs.pulseaudio;

    # ── Kiosk user and group ───────────────────────────────────────────────
    users.groups.kiosk = { };
    users.users.kiosk = {
      isNormalUser = true;
      home = kioskHome;
      createHome = true;
      group = "kiosk";
      description = "Kiosk VNC session user";
    };

    # ── Activation: write the xstartup script into the kiosk home ─────────
    system.activationScripts.kiosk-vnc-xstartup = {
      text = ''
        install -d -m 750 -o kiosk -g kiosk ${kioskHome}/.vnc
        install -m 755 -o kiosk -g kiosk \
          ${xstartupScript} \
          ${kioskHome}/.vnc/xstartup
      '';
    };

    # ── Systemd service: Xvnc session ─────────────────────────────────────
    # Xvnc acts as both the X11 display server and the VNC server in one
    # process. When a VNC client connects, it runs ~/.vnc/xstartup which
    # launches the application. The session ends when the app exits.
    systemd.services.app-vnc = {
      description = "Kiosk VNC session (${cfg.app.package.name or "app"} on :${displayNum})";
      wantedBy = [ "multi-user.target" ];
      after = [ "network.target" ];

      # Run as the kiosk user; forking because vncserver daemonises itself.
      serviceConfig = {
        User = "kiosk";
        Group = "kiosk";
        Type = "forking";
        PIDFile = "${kioskHome}/.vnc/%H:${displayNum}.pid";

        # Ensure the .vnc directory exists before starting
        ExecStartPre = "${pkgs.coreutils}/bin/mkdir -p ${kioskHome}/.vnc";

        # vncserver wraps Xvnc: starts a virtual display and VNC listener.
        # -SecurityTypes None  → no VNC password (Tailscale/bridge isolation is the boundary)
        # -localhost no        → bind on all interfaces (controlled by vnc.listenHost behaviour)
        # -rfbport             → explicit port (avoids scanning for next free port)
        ExecStart = "${pkgs.tigervnc}/bin/vncserver :${displayNum} -geometry ${displayWidth}x${displayHeight} -depth ${displayDepth} -SecurityTypes None -localhost no -rfbport ${vncPort}";

        ExecStop = "${pkgs.tigervnc}/bin/vncserver -kill :${displayNum}";

        Restart = "always";
        RestartSec = "5s";
      };
    };

    # ── PulseAudio null-sink (optional audio forwarding) ──────────────────
    # Runs a virtual output device. Guacamole's guacd connects to it over TCP
    # and streams audio to the browser. Configure the matching port in
    # frgd.services.guacamole.connections.<name>.audioPort on the host.
    hardware.pulseaudio = mkIf cfg.audio.enable {
      enable = true;
      extraConfig = ''
        # Virtual output — no real sound card needed in the container.
        load-module module-null-sink sink_name=virtual_output sink_properties=device.description="VirtualOutput"
        set-default-sink virtual_output

        # Allow guacd on the host to connect anonymously over TCP.
        load-module module-native-protocol-tcp auth-anonymous=1 port=${toString cfg.audio.port}
      '';
    };

    # ── Firewall: disabled in containers (LXD bridge provides isolation) ──
    networking.firewall.enable = mkForce false;
  };
}
