# Auto-generated by compose2nix.

{ pkgs, lib, config, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [ 53 ];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."obsidian" = {
    image = "lscr.io/linuxserver/obsidian:latest";
    environment = {
      "PGID" = "1000";
      "PUID" = "1000";
      "TZ" = "Americas/Chicago";
    };
    volumes = [
      "/home/justin/notes/config:/config:rw"
    ];
    ports = [
      "3000:3000/tcp"
      "3001:3001/tcp"
      "27124:27124/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=obsidian"
      "--network=obsidian-notes_default"
      "--shm-size=1073741824"
    ];
  };
  systemd.services."podman-obsidian" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-obsidian-notes_default.service"
    ];
    requires = [
      "podman-network-obsidian-notes_default.service"
    ];
    partOf = [
      "podman-compose-obsidian-notes-root.target"
    ];
    wantedBy = [
      "podman-compose-obsidian-notes-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-obsidian-notes_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f obsidian-notes_default";
    };
    script = ''
      podman network inspect obsidian-notes_default || podman network create obsidian-notes_default
    '';
    partOf = [ "podman-compose-obsidian-notes-root.target" ];
    wantedBy = [ "podman-compose-obsidian-notes-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-obsidian-notes-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
